---
permalink: online-help/reference-relationship-last-1-month-transfer-rate-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vue relation : taux de transfert du dernier mois vous permet d"analyser la quantité de volume de données qui est transférée au quotidien pour les volumes dans des relations asynchrones. Cette page fournit également des détails sur les transferts de volume quotidiens et sur le temps nécessaire à l"exécution de l"opération de transfert.' 
---
= Relation : vue du taux de transfert du dernier mois
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vue relation : taux de transfert du dernier mois vous permet d'analyser la quantité de volume de données qui est transférée au quotidien pour les volumes dans des relations asynchrones. Cette page fournit également des détails sur les transferts de volume quotidiens et sur le temps nécessaire à l'exécution de l'opération de transfert.

Les commandes situées en haut de la page vous permettent de sélectionner une vue particulière (pour l'intégrité, les performances, la capacité, etc.), d'effectuer des recherches pour localiser des objets spécifiques, de créer et d'appliquer des filtres pour restreindre la liste des données affichées, ajouter/supprimer/réorganiser des colonnes sur la page, et exportez les données de la page vers un `.csv`, `.pdf`, ou `.xlsx` fichier. Après avoir personnalisé la page, vous pouvez enregistrer les résultats sous forme de vue personnalisée, puis planifier régulièrement un rapport de ces données à générer et à envoyer par e-mail.

* *Taille totale du transfert*
+
Affiche la taille totale du transfert de volume en gigaoctets.

* *Jour*
+
Affiche le jour où le transfert de volume a été lancé.

* *Heure de fin*
+
Affiche l'heure de fin du transfert de volume avec date.


