---
permalink: online-help/reference-relationship-last-1-month-transfer-status-view.html 
sidebar: sidebar 
keywords:  
summary: 'La vue relation : état du transfert du dernier mois vous permet d"analyser les tendances de transfert du volume sur une période de temps pour les volumes des relations asynchrones. Cette page indique également si le transfert de volume a réussi ou échoué.' 
---
= Relation : vue État transfert du dernier mois
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La vue relation : état du transfert du dernier mois vous permet d'analyser les tendances de transfert du volume sur une période de temps pour les volumes des relations asynchrones. Cette page indique également si le transfert de volume a réussi ou échoué.

Les commandes situées en haut de la page vous permettent de sélectionner une vue particulière (pour l'intégrité, les performances, la capacité, etc.), d'effectuer des recherches pour localiser des objets spécifiques, de créer et d'appliquer des filtres pour restreindre la liste des données affichées, ajouter/supprimer/réorganiser des colonnes sur la page, et exportez les données de la page vers un `.csv`, `.pdf`, ou `.xlsx` fichier. Après avoir personnalisé la page, vous pouvez enregistrer les résultats sous forme de vue personnalisée, puis planifier régulièrement un rapport de ces données à générer et à envoyer par e-mail.

* *Volume source*
+
Affiche le nom du volume source.

* *Volume de destination*
+
Affiche le nom du volume de destination.

* *Type d'opération*
+
Affiche le type de transfert de volume.

* *Résultat d'opération*
+
Indique si le transfert de volume a réussi.

* *Heure de début du transfert*
+
Affiche l'heure de début du transfert de volume.

* *Heure de fin du transfert*
+
Affiche l'heure de fin du transfert de volume.

* *Durée du transfert*
+
Affiche le temps nécessaire (en heures) pour terminer le transfert de volume.

* *Taille de transfert*
+
Affiche la taille (en Mo) du volume transféré.

* *SVM source*
+
Affiche le nom de la machine virtuelle de stockage (SVM).

* *Cluster source*
+
Affiche le nom du cluster source.

* *SVM de destination*
+
Affiche le nom du SVM de destination.

* *Cluster de destination*
+
Affiche le nom du cluster de destination.


