---
permalink: online-help/reference-snapmirror-and-vault-relationship-events.html 
sidebar: sidebar 
keywords:  
summary: 'Les événements liés aux relations entre SnapMirror et Vault vous fournissent des informations sur l"état de vos relations SnapMirror et Vault asynchrones, qui vous permettent de surveiller et contrôler les éventuels problèmes. Les événements sont regroupés par zone d"impact et incluent le nom de l"événement et de l"interruption, le niveau d"impact, le type de source et la gravité.' 
---
= Événements relatifs aux relations SnapMirror et Vault
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les événements liés aux relations entre SnapMirror et Vault vous fournissent des informations sur l'état de vos relations SnapMirror et Vault asynchrones, qui vous permettent de surveiller et contrôler les éventuels problèmes. Les événements sont regroupés par zone d'impact et incluent le nom de l'événement et de l'interruption, le niveau d'impact, le type de source et la gravité.



== Zone d'impact : protection

|===
| Nom de l'événement(Nom du piège) | Niveau d'impact | Type de source | Gravité 


 a| 
Asynchrone Mirror et Vault malsains (ocumEvtMirrorVaultRelationshipHealthy)
 a| 
Risques
 a| 
Relation SnapMirror
 a| 
Avertissement



 a| 
Désactivation du miroir asynchrone et du coffre-fort (ocumEvtMirrorVaultRelationshipStateBrokenoff)
 a| 
Risques
 a| 
Relation SnapMirror
 a| 
Erreur



 a| 
Échec de l'initialisation du miroir asynchrone et du coffre-fort (ocumEvtMirrorVaultRelationshipInitializeFailed)
 a| 
Risques
 a| 
Relation SnapMirror
 a| 
Erreur



 a| 
Échec de la mise à jour asynchrone du miroir et du coffre-fort (ocumEvtMirrorVaultRelationshipUpdateFailed)
 a| 
Risques
 a| 
Relation SnapMirror
 a| 
Erreur



 a| 
Erreur de décalage asynchrone du miroir et du coffre-fort (ocumEvtMirrorVaultRelationshipLagError)
 a| 
Risques
 a| 
Relation SnapMirror
 a| 
Erreur



 a| 
Avertissement : mise en miroir asynchrone et décalage du coffre-fort (ocumEvtMirrorVaultRelationshipLagWarning)
 a| 
Risques
 a| 
Relation SnapMirror
 a| 
Avertissement



 a| 
Échec de la resynchronisation asynchrone du miroir et du coffre-fort (ocumEvtMirrorVaultRelationshipResyncFailed)
 a| 
Risques
 a| 
Relation SnapMirror
 a| 
Erreur

|===