---
settings:
  name: Active IQ Unified Manager 9.8
  downlevel: true
  internal:
    pdf-enabled: true
    lipi-enabled: true
  prod:
    pdf-enabled: true
    harmony_enabled: false
  versions:
  - version-number: '9.8'
    url: "/active-iq-unified-manager-98"
  - version-number: '9.9'
    url: "/active-iq-unified-manager-99"
  - version-number: '9.7'
    url: "/active-iq-unified-manager-97"
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation Active IQ Unified Manager 9.8
    url: "/index.html"
  - title: Notes de mise à jour
    url: "/release-notes.html"
  - title: Commencez
    entries:
    - title: Installation de démarrage rapide pour VMware vSphere
      url: "/qsg-vapp.html"
    - title: Installation de démarrage rapide pour Linux
      url: "/qsg-linux.html"
    - title: Installation de démarrage rapide pour Windows
      url: "/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: Mentions légales
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Commencez
    links:
    - title: Notes de mise à jour
      url: "/release-notes.html"
    - title: Installation de démarrage rapide pour VMware vSphere
      url: qsg-vapp.html
    - title: Installation de démarrage rapide pour Linux
      url: qsg-linux.html
    - title: Installation de démarrage rapide pour Windows
      url: qsg-windows.html
  - title: Installer configurer Unified Manager
    links:
    - title: Installez la mise à niveau sur les systèmes VMware vSphere
      url: install-vapp/concept-requirements-for-installing-unified-manager.html
    - title: Installez la mise à niveau sur les systèmes Linux
      url: install-linux/concept-requirements-for-installing-unified-manager.html
    - title: Installez la mise à niveau sur les systèmes Windows
      url: install-windows/concept-requirements-for-installing-unified-manager.html
    - title: Configurez Unified Manager
      url: config/concept-configuring-unified-manager.html
  - title: Contrôle des performances
    links:
    - title: Seuils de performances
      url: performance-checker/concept-managing-performance-thresholds.html
    - title: Performances du cluster
      url: performance-checker/concept-monitoring-cluster-performance-from-the-dashboard.html
    - title: Groupe de règles de QoS
      url: performance-checker/concept-managing-performance-using-qos-policy-group-information.html
  - title: Surveillance de la protection des données
    links:
    - title: Configuration de la relation de protection
      url: "/data-protection/task-setting-up-protection-relationships-in-unified-manager.html"
    - title: Effectuez les opérations de basculement et de rétablissement
      url: "/data-protection/task-performing-a-protection-relationship-failover-and-failback.html"
    - title: Gérer la relation de protection
      url: "/data-protection/concept-managing-and-monitoring-protection-relationships.html"
    - title: Générer des rapports
      url: "/reporting/concept-unified-manager-reporting.html"
  - title: Utilisez des API REST
    links:
    - title: Commencez
      url: "/api-automation/concept-api-url-and-categories.html"
    - title: Accès à l'API REST et authentification dans Active IQ Unified Manager
      url: "/api-automation/concept-rest-api-access-and-authentication-in-oncommand-api-services.html"
    - title: Accédez aux API ONTAP
      url: "/api-automation/concept-gateway-apis.html"
  - title: Ressources supplémentaires
    links:
    - title: Vidéos sur Unified Manager
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
    - title: Blogs Unified Manager
      url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish-date-mktg%20descending&layout=card&f:@facet-language-mktg=[English]
    - title: Documentation relative à la dernière version de Active IQ Unified Manager
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
