---
permalink: health-checker/concept-backup-and-restore-using-netapp-snapshots.html 
sidebar: sidebar 
keywords:  
summary: 'La sauvegarde NetApp Snapshot crée une image instantanée de la base de données Unified Manager et des fichiers de configuration qui permet de restaurer des données en cas de défaillance du système ou de perte de données. Vous pouvez planifier régulièrement l"écriture d"une sauvegarde Snapshot sur un volume de l"un de vos clusters ONTAP, afin de toujours disposer d"une copie à jour.' 
---
= Sauvegarde et restauration à l'aide des copies NetApp snapshots
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La sauvegarde NetApp Snapshot crée une image instantanée de la base de données Unified Manager et des fichiers de configuration qui permet de restaurer des données en cas de défaillance du système ou de perte de données. Vous pouvez planifier régulièrement l'écriture d'une sauvegarde Snapshot sur un volume de l'un de vos clusters ONTAP, afin de toujours disposer d'une copie à jour.

[NOTE]
====
Cette fonctionnalité est disponible uniquement lorsque Unified Manager est installé sur un serveur Red Hat Enterprise Linux ou CentOS Linux.

====
Les sauvegardes Snapshot prennent très peu de temps, en général quelques minutes seulement, et la base de données Unified Manager est verrouillée pendant un très court laps de temps. Vous n'avez donc que peu d'interruptions dans votre installation. L'image consomme un espace de stockage minimal et entraîne une surcharge minime des performances, car elle enregistre uniquement les modifications apportées aux fichiers depuis la dernière copie Snapshot. Comme la copie Snapshot est créée sur un cluster ONTAP, vous pouvez utiliser d'autres fonctionnalités NetApp, telles que SnapMirror, pour créer une protection secondaire, si nécessaire.

Avant de lancer une opération de sauvegarde, Unified Manager effectue une vérification d'intégrité afin de vérifier que le système de destination est disponible.

Notez que vous ne pouvez restaurer une sauvegarde Snapshot que sur la même version d'Unified Manager. Par exemple, si vous avez créé une sauvegarde sur Unified Manager 9.8, la sauvegarde ne peut être restaurée que sur les systèmes Unified Manager 9.8.
