---
permalink: health-checker/concept-configuring-the-destination-and-schedule-for-database-dump-backups.html 
sidebar: sidebar 
keywords:  
summary: Vous pouvez configurer les paramètres de sauvegarde de vidage de la base de données Unified Manager pour définir le chemin de sauvegarde de la base de données, le nombre de rétention et la planification des sauvegardes. Vous pouvez activer des sauvegardes planifiées quotidiennement ou hebdomadaires. Par défaut, les sauvegardes planifiées sont désactivées, mais vous devez définir un planning de sauvegarde. 
---
= Configuration de la destination et de la planification pour les sauvegardes de vidage de base de données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer les paramètres de sauvegarde de vidage de la base de données Unified Manager pour définir le chemin de sauvegarde de la base de données, le nombre de rétention et la planification des sauvegardes. Vous pouvez activer des sauvegardes planifiées quotidiennement ou hebdomadaires. Par défaut, les sauvegardes planifiées sont désactivées, mais vous devez définir un planning de sauvegarde.



== Avant de commencer

* Vous devez avoir le rôle opérateur, administrateur d'applications ou administrateur de stockage.
* Vous devez disposer d'au moins 150 Go d'espace disponible dans l'emplacement que vous définissez comme chemin de sauvegarde.
+
Il est recommandé d'utiliser un emplacement distant externe au système hôte Unified Manager.

* Lorsque Unified Manager est installé sur un système Linux, vérifiez que l'utilisateur « jboss » dispose des autorisations d'écriture sur le répertoire de sauvegarde.
* Vous ne devez pas planifier d'opérations de sauvegarde immédiatement après l'ajout d'un nouveau cluster alors que Unified Manager collecte 15 jours de données historiques de performance.




== Description de la tâche

La première sauvegarde est effectuée moins de temps que les sauvegardes suivantes, car la première sauvegarde est une sauvegarde complète. Une sauvegarde complète peut dépasser 1 Go et peut prendre entre trois et quatre heures. Les sauvegardes suivantes sont incrémentielles et requièrent moins de temps.

[NOTE]
====
Si vous constatez que le nombre de fichiers de sauvegarde incrémentielle est trop important pour l'espace que vous avez alloué aux sauvegardes, vous pouvez régulièrement créer une nouvelle sauvegarde complète pour remplacer l'ancienne sauvegarde complète et tous les fichiers incrémentiels enfant. Autre option, il est possible de commencer à utiliser la méthode de sauvegarde NetApp Snapshot si Unified Manager est installé sur un système Linux.

====


== Étapes

. Dans le volet de navigation de gauche, cliquez sur *général* > *sauvegarde de base de données*.
. Dans la page *sauvegarde de base de données*, cliquez sur *Paramètres de sauvegarde*.
. Configurez les valeurs appropriées pour un chemin de sauvegarde, le nombre de rétention et la planification.
+
La valeur par défaut pour le nombre de rétention est 10 ; vous pouvez utiliser 0 pour créer des sauvegardes illimitées.

. Sélectionnez le bouton *planifié quotidien* ou *planifié hebdomadaire*, puis spécifiez les détails de l'horaire.
. Cliquez sur *appliquer*.




== Résultats

Les fichiers de sauvegarde de vidage de la base de données sont créés en fonction de la planification. Vous pouvez voir les fichiers de sauvegarde disponibles dans la page sauvegarde de la base de données.

*Informations connexes*

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_start_a_new_Incremental_Backup_chain_within_ActiveIQ_Unified_Manager_versions_7.2_through_9.6["Comment démarrer une nouvelle chaîne de sauvegarde incrémentielle au sein de Active IQ Unified Manager"]
